/**
 * The blocks.
 *
 * The PHPUnit suite already proves the render callbacks return the same markup
 * the shortcodes return, that the hidden-plugins setting is honoured either way,
 * and that neither entry point is implemented in terms of the other. Repeating
 * any of that here would buy nothing. What only a browser can answer is whether
 * the *built* JavaScript works: `build/` is generated by bin/build and is not in
 * the repository, so every assertion below is also an assertion that the build
 * ran and produced something a browser can load.
 *
 * Two things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers all three blocks -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else;
 * * the editor preview is the real listing, which is what proves the blocks get
 *   their preview from core's block-renderer route and earn none of their own.
 *
 * The front-end pass is one test rather than three, because the interesting
 * question there is only whether a saved block comment reaches the renderer at
 * all -- what the listing then says is settled in shortcodes.spec.js against the
 * same markup.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
const {
	clearFilterHidden,
	createShortcodePost,
	deleteOptions,
	installedPlugins,
	removeHostilePlugin,
	summary,
	uniqueTitle,
} = require( './helpers.js' );

/** The three blocks this plugin registers. */
const STATS_BLOCK = 'wp-pluginsused/stats-pluginsused';
const ACTIVE_BLOCK = 'wp-pluginsused/active-pluginsused';
const INACTIVE_BLOCK = 'wp-pluginsused/inactive-pluginsused';

/** What the install actually holds, read once and shared by every test here. */
let plugins;

test.describe( 'The blocks', () => {
	test.beforeAll( async ( { requestUtils } ) => {
		await requestUtils.deleteAllPosts();

		// Anything an earlier run left behind would change what the listings
		// say, so the install starts from a known state.
		removeHostilePlugin();
		deleteOptions();
		clearFilterHidden();

		plugins = installedPlugins();
	} );

	test.afterAll( async () => {
		deleteOptions();
	} );

	test.describe( 'in the editor', () => {
		test( 'all three blocks are registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and none of
			// these is here -- which is the failure this whole file exists for.
			expect( names ).toContain( STATS_BLOCK );
			expect( names ).toContain( ACTIVE_BLOCK );
			expect( names ).toContain( INACTIVE_BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'pluginsused/active-pluginsused' );
		} );

		test( 'the listing block previews the real listing', async ( {
			admin,
			editor,
		} ) => {
			await admin.createNewPost();
			await editor.insertBlock( { name: ACTIVE_BLOCK } );

			// The preview is core's ServerSideRender, which posts to
			// /wp/v2/block-renderer/ and draws what the front end would draw.
			// Seeing the site's own active plugins here is what proves the block
			// earns no REST route of its own.
			await expect(
				editor.canvas.locator( `[data-type="${ ACTIVE_BLOCK }"]` ),
			).toContainText( plugins.active[ 0 ] );
		} );

		test( 'the summary block previews the summary', async ( {
			admin,
			editor,
		} ) => {
			await admin.createNewPost();
			await editor.insertBlock( { name: STATS_BLOCK } );

			await expect(
				editor.canvas.locator( `[data-type="${ STATS_BLOCK }"]` ),
			).toContainText(
				summary( plugins.active.length, plugins.inactive.length ),
			);
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a page holding all three blocks renders all three', async ( {
			page,
			requestUtils,
		} ) => {
			const post = await createShortcodePost(
				requestUtils,
				`<!-- wp:${ STATS_BLOCK } /-->\n\n` +
					`<!-- wp:${ ACTIVE_BLOCK } /-->\n\n` +
					`<!-- wp:${ INACTIVE_BLOCK } /-->`,
				uniqueTitle( 'Blocks' ),
			);

			await page.goto( post.link );

			const content = page.locator( '.entry-content' );

			await expect( content ).toContainText(
				summary( plugins.active.length, plugins.inactive.length ),
			);
			await expect( content ).toContainText( plugins.active[ 0 ] );
			await expect( content ).toContainText( plugins.inactive[ 0 ] );
		} );
	} );
} );
